# Generated by Django 6.0.5 on 2026-05-19 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='expiration_date',
            field=models.DateField(blank=True, help_text="Automatically calculated from the chosen plan's duration if left blank.", null=True),
        ),
    ]
